name: spread-github-announcements
on:
  discussion:
    types: [created]
jobs:
  spread:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          DISCORD_ANNOUNCEMENTWEBHOOK: ${{ secrets.DISCORD_ANNOUNCEMENTWEBHOOK }}
        with:
          script: |
            const discussion = context.payload.discussion
            const isAnnouncement = discussion.category.node_id === 'DIC_kwDOF2FhEs4CQX_F'
            const discordAnnouncementWebhook = process.env.DISCORD_ANNOUNCEMENTWEBHOOK

            if(isAnnouncement && discordAnnouncementWebhook){
              fetch(new Request(discordAnnouncementWebhook, {
                method: 'POST',
                headers: new Headers({
                  'Accept': 'application/json',
                  'Content-Type': 'application/json'
                }),
                body: JSON.stringify({
                  content: '['+discussion.title+']('+discussion.html_url+')'
                })
              }))
            }

            return new Response(null, {headers: {...headers}})
