name: spread-github-announcements
on:
  discussion:
    types: [created]
jobs:
  spread:
    runs-on: ubuntu-latest
    steps:
      - name: CompileMessage
        uses: actions/github-script@v6
        with:
          script: |
            const discussion = context.payload.discussion
            const isAnnouncement = discussion.category.node_id === 'DIC_kwDOF2FhEs4CQX_F'
            if(isAnnouncement){
                return '['+discussion.title+']('+discussion.html_url+')'
            }
            throw new Error('Invalid call')
          result-encoding: string
      - name: SpreadMessage
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.DISCORD_ANNOUNCEMENTWEBHOOK }}'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content": "${{steps.CompileMessage.outputs.result}}"}'
